"""Public policies reflecting the platform's existing behavior."""
import os
from flask import Blueprint, render_template
legal = Blueprint('legal', __name__)
UPDATED = '11 October 2026'
PAGES = {
'privacy': ('Privacy Policy', 'How GameArena uses and protects your information.', [
('Who this policy covers', ["This policy covers GameArena accounts, tournaments, chat, wallets and Pro memberships. GameArena operates at gamearena01.com. Contact the GameArena team using the details below for questions or privacy requests."]),
('Information we collect', ["Account information includes your username, email, verification status and authentication identifiers. With local authentication, passwords are stored as hashes; verification and reset records are also stored. With managed authentication enabled, the authentication provider handles sign-in credentials.", "Profile information may include an avatar, bio, game IDs, preferred games and settings you choose to provide. We also store tournament entries, match results, room details, result evidence, achievements, saved tournaments and player connections.", "We store messages, read status, notifications, support requests and moderation reports. Messages are stored by GameArena and are not end-to-end encrypted. Deleting a message may hide its content in the conversation while retaining a record for moderation or technical purposes.", "Payment records include transaction references, amounts, status, wallet activity and subscription records. Payout information may include your bank, account number and account name. Paystack processes payment credentials; GameArena does not receive or store your full card number or card security code.", "Operational information includes request timestamps, IP-based security and rate-limit records, server logs, browser notification subscriptions and error records. Do not send passwords, verification codes or payment secrets in chat or support messages."]),
('Why we use information', ["We use information to operate accounts, verify access, organise tournaments, confirm payments, manage subscriptions and payouts, deliver requested notifications, respond to support requests, prevent abuse and resolve disputes. We rely on the appropriate basis for each activity: providing the service you request, legal obligations, legitimate interests in security and fair play, or consent for optional notifications and marketing where applicable. Optional marketing is separate from using GameArena."]),
('What other players can see', ["Your public profile, username, selected avatar, recorded results and membership badge may be visible to other players. You can change profile visibility and messaging preferences in Settings. Tournament results and information required to run an event may remain visible separately from your profile. Direct messages are available to their participants; public or tournament chats are visible to the people permitted into those spaces. Administrators may access stored records as needed for support, moderation and disputes."]),
('Providers and disclosure', ["GameArena uses Render for hosting, Supabase PostgreSQL for database storage, Paystack for payment processing, and configured email or notification services for delivery. Supabase Auth or Google sign-in may also process account information when enabled. We share the information needed for those services, investigate abuse, fulfil legal obligations or protect users. We do not sell personal information. Providers may process information outside Nigeria, subject to applicable transfer requirements and safeguards."]),
('Cookies and device storage', ["Session cookies keep you signed in and protect forms. Local browser storage remembers choices such as your theme; session storage remembers dismissed prompts. The service worker caches public assets for the installed app. Browser push subscriptions are stored when you enable notifications. You can clear browser storage, revoke notifications and log out; doing so may reset preferences or affect functionality."]),
('Retention and security', ["We keep records for as long as needed to provide the service, investigate disputes and meet financial, security or legal requirements. Retention depends on the record type; we do not promise that a message or financial record is immediately erased when you remove it from the interface. Access controls, password hashing and protected payment verification help safeguard data. No service can guarantee absolute security."]),
('Your choices and requests', ["You can edit your profile and preferences in Settings, block players, manage notifications and cancel subscription renewal through the membership page when billing is enabled. Contact us to request access, correction, deletion, restriction, portability or to object to processing, subject to applicable law. We may need to verify your identity; do not send your password. Deletion may be limited by records needed for legal obligations, transactions, security or unresolved disputes. Account deletion is currently handled through support rather than a self-service button. You can also complain to the Nigeria Data Protection Commission at ndpc.gov.ng."]),
('Changes', ["We will update the date on this page when the policy changes. Material changes should be communicated through the service or an appropriate account notice before they take effect where required."])
]),
'terms': ('Terms of Use', 'Account, competition and membership agreements.', [
('Using GameArena', ["These terms govern your use of GameArena. By creating an account or using its services, you agree to follow these terms and the rules published for each tournament. Read the Privacy Policy to understand how your information is used. If you do not agree, do not use the service. Rights you have under applicable law are not excluded by these terms."]),
('Accounts and eligibility', ["Provide accurate account and payout information, keep your sign-in details secure and do not impersonate another player. You are responsible for activity you authorise on your account. Do not share verification codes. Each tournament may set its own game, region, age, roster and eligibility requirements. Enter paid events or purchase memberships only if you can lawfully do so and meet the applicable eligibility rules. Do not use GameArena where participation is prohibited."]),
('Tournament rules and fair play', ["Read the event page before joining: entry fee, schedule, capacity, format, game requirements, prize information and result procedure apply to that event. A successful payment must be verified before a paid entry is confirmed. A pending entry is not proof of confirmed participation.", "No cheating, unauthorised tools, fabricated results, account impersonation, collusion, harassment or abuse. Protect room credentials and follow organiser instructions. Submit truthful result evidence and use the dispute process when a result is contested. Moderation or disqualification should be based on the event rules and supporting information; report mistakes through support.", "GameArena organises competitions but does not operate the underlying game servers. Publisher rules still apply. Connection failures, game outages and event changes can affect play; check the event page and contact support about cancellations or significant changes. Winning is never guaranteed."]),
('Payments, prizes and wallets', ["Paystack handles supported payments. Check the amount and any displayed charges before authorising a payment. GameArena confirms payment server-side; a receipt alone may not immediately update an entry if verification is delayed. If charged while still pending, use the payment verification option or contact support with the transaction reference before paying again.", "Wallet entries and prize records depend on confirmed transactions and results. Withdrawals require valid payout details and provider processing; processing times may vary. Do not use the wallet as a bank account, transfer funds fraudulently or submit someone else's bank information without authority."]),
('Refunds and payment disputes', ["Contact support with your account, tournament name and payment reference for duplicate charges, a cancelled event, a payment error or an undelivered service. Refund eligibility is assessed against the circumstances, published event terms and applicable consumer rights. A payment is not automatically refunded by leaving a tournament or deleting an account. Approved refunds depend on the payment provider's processing. Do not make another payment while an existing charge is being investigated unless support confirms it is necessary."]),
('Pro subscription agreement', ["When Master checkout is available, the price is NGN 2,300 per month with automatic monthly renewal. You must expressly agree to the recurring charge at checkout. A local preview or disabled checkout does not collect payment. Access starts only after a successful payment is verified.", "Cancel automatic renewal through the Pro membership controls when your subscription is available there, or contact support if you cannot access those controls. Cancellation is effective when confirmed by the payment provider; you keep paid access until its expiry. Failed renewal can end premium access after the paid period. Cancellation does not itself refund a completed charge.", "Master includes the benefits shown as available on its page. Grandmaster and Legendary are planned tiers and are not currently sold. Membership badges identify subscriptions, not identity verification or competitive rank. Membership does not improve rankings, matchmaking priority or dispute decisions. Any future price or material benefit change must be explained before the affected purchase or renewal, with an opportunity to cancel where required."]),
('Chat and community rules', ["Do not send threats, hateful content, sexual exploitation material, scams, spam, private information without permission or content you do not have the right to share. Respect messaging restrictions, player requests and blocks. New accounts may send one introductory message before a request is accepted; existing accounts may retain their earlier messaging permissions. Privacy settings and blocks still apply. Report abuse through the available conversation controls or support."]),
('Your content and moderation', ["You retain rights in content you upload. You give GameArena permission to store, display and process that content as necessary to operate the features you use and investigate reports. Do not upload material that infringes someone else's rights. GameArena may restrict content or accounts for rule violations, security or legal reasons. Contact support to ask for a review of an action affecting you."]),
('Availability and responsibility', ["GameArena may experience maintenance, provider outages and delays. We do not promise uninterrupted service, a particular result or instant payment processing. We remain responsible where applicable law requires it; these terms do not exclude mandatory consumer rights or liability that cannot lawfully be excluded. Tell support promptly about unauthorised account activity or a service error."]),
('Questions and changes', ["Use the contact details below for disputes, questions and account issues. These terms are intended for GameArena's operation in Nigeria and apply subject to mandatory applicable law. Updated terms will show a new date; material changes should be communicated appropriately before they take effect. Individual event rules cannot remove rights protected by law."])
]),
'faq': ('Frequently Asked Questions', 'Quick answers about accounts, tournaments and Pro.', [
('How do I join a tournament?', ["Create an account, verify your email, open the tournament page and check its rules. Free entries can be confirmed without payment. Paid entries become participants after payment verification. Capacity and registration status still apply."]),
('I paid, but my entry says pending. What next?', ["Do not pay twice. Open your existing entry or payment verification link. If it remains pending, contact support with the Paystack reference, event name and account email. Never share your card details or verification codes."]),
('Where are my match room details?', ["Check the tournament and match pages after your entry is confirmed. Room information depends on the organiser's schedule and the access rules for that match."]),
('How do results, prizes and disputes work?', ["Follow the result submission and confirmation instructions for the event. Rankings use recorded results. Report contested results through the match dispute process or support; prize and wallet updates depend on confirmation."]),
('Can I get a refund?', ["Contact support about duplicate payments, cancellations, payment errors or an undelivered service. Include the reference and event. Refunds are reviewed against the event terms and applicable rights; removing an entry does not automatically refund it."]),
('How much is Master, and does it renew?', ["Master is NGN 2,300 per month when paid checkout is enabled. It renews automatically after your explicit agreement. Local preview access is for testing and does not charge you. Use Pro to manage payment details and cancel renewal; confirmed cancellation keeps access until the paid period ends."]),
('Can I subscribe to Grandmaster or Legendary?', ["Not yet. Those cards describe planned features and are marked Coming soon. Only benefits shown as available should be treated as part of a current membership."]),
('Do I need Pro to compete or message players?', ["No. Standard tournaments, recorded results, basic profiles and permitted messaging remain available without Pro. Pro does not buy a higher competitive rank."]),
('Why can I send only one message to a new player?', ["Player requests protect new accounts from unsolicited messages. A first introduction can go into Requests; further messages require acceptance. Earlier accounts may retain existing messaging permissions. Settings and blocking can also restrict messages."]),
('How do I change privacy, notifications or the theme?', ["Open Settings. Choose profile visibility, messaging permissions and notification preferences there. Light or dark theme saves immediately. Browser push permission can also be changed in your browser or device settings."]),
('Can I delete my account or request my data?', ["Contact GameArena support or the privacy contact below. Requests are handled manually and may require identity verification. Some transaction, security or dispute records may need to be retained."]),
('Why does the first visit sometimes take longer?', ["Hosting wake-up time, your connection and service providers can delay the first request. Subsequent visits can reuse cached public assets. If a payment is involved, check its existing status before retrying."]),
('How do I contact support?', ["Signed-in users can open Help & support and send a message to the team. If you cannot sign in, use the email below. Include what happened, the relevant event and a payment reference if applicable; never include passwords or payment secrets."])
])}

@legal.route('/privacy')
@legal.route('/privacy-policy')
def privacy(): return show('privacy')
@legal.route('/terms')
@legal.route('/terms-of-use')
def terms(): return show('terms')
@legal.route('/faq')
def faq(): return show('faq')
def show(key):
    title, description, sections = PAGES[key]
    return render_template('legal.html', title=title, description=description, sections=sections, updated=UPDATED, contact_email=os.environ.get('GAMEARENA_SUPPORT_EMAIL', 'jegzdami@gmail.com'))
